set -e
/opt/anaconda3/bin/python3 scripts/identity/restamp_social_ids.py
/opt/anaconda3/bin/python3 scripts/identity/restamp_delving_ids.py
/opt/anaconda3/bin/python3 scripts/02_process/resolve_commits.py
/opt/anaconda3/bin/python3 scripts/02_process/reviews.py
/opt/anaconda3/bin/python3 scripts/02_process/github_social.py
/opt/anaconda3/bin/python3 scripts/02_process/merge_social.py
/opt/anaconda3/bin/python3 scripts/02_process/governance.py
/opt/anaconda3/bin/python3 scripts/04_deliver/registry.py
/opt/anaconda3/bin/python3 scripts/02_process/categorize.py
/opt/anaconda3/bin/python3 scripts/03_analyze/review_metrics.py
/opt/anaconda3/bin/python3 scripts/03_analyze/influence.py
/opt/anaconda3/bin/python3 scripts/03_analyze/expertise.py
/opt/anaconda3/bin/python3 scripts/03_analyze/unify_contributors.py
/opt/anaconda3/bin/python3 scripts/04_deliver/generate_regional_evolution.py
/opt/anaconda3/bin/python3 scripts/04_deliver/registry.py
/opt/anaconda3/bin/python3 scripts/04_deliver/tracker_artifacts.py
/opt/anaconda3/bin/python3 scripts/04_deliver/ui_artifacts.py
/opt/anaconda3/bin/python3 scripts/04_deliver/ecosystem_summary.py
/opt/anaconda3/bin/python3 scripts/04_deliver/discussions_pulse.py
/opt/anaconda3/bin/python3 scripts/04_deliver/network_home_snapshot.py
